server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost/files"
    username: "root"
    password: "4788"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# view location
view:
  spring:
    thymeleaf:
      suffix: .html

# encoding korean
encoding:
  spring:
    http:
      encoding:
        charset: UTF-8
    servlet:
      filter:
        character:
          encoding:
            enabled: true
            force-request: true
            force-response: true
            encoding: UTF-8
            force: true